engines:
  eslint:
    enabled: false
  duplication:
    enabled: false
exclude_paths:
- "gulpfile.js"
- "README.md"
- "examples/**"
- "package.json"
- "packages/*/test/**/*"
- "packages/*/dist/**/*"
